# Basic Stuff
title = "Subho Sankar Banerjee"
googleAnalytics = "G-VGWDWM7F6S"
baseURL = "https://ssbanerje.github.io"
locale = "en-us"
enableRobotsTXT = true

# Taxonomies
disableKinds = ["term", "taxonomy"]

# Markdown & Rendering
buildFuture = true
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    guessSyntax = true
    style = "manni"

# Site parameters
[params]
  showFeatured = true

# SEO Stuff
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

