---

name: Github Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ssbanerje-hugo .

      - name: Build Webpage
        run: docker run --rm -v ${{ github.workspace }}:/src -w /src ssbanerje-hugo make all

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
